// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZO1.Tutorials.Core.Contexts;

namespace ZO1.Tutorials.Core.Migrations
{
    [DbContext(typeof(BorrowedContext))]
    [Migration("20211221164705_AddLenderAndItemNameColsToItemsTable")]
    partial class AddLenderAndItemNameColsToItemsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZO1.Tutorials.Core.Models.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Lender")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BorrowerName = "Dennis",
                            ItemName = "Book",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            BorrowerName = "Frank",
                            ItemName = "Phone",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            BorrowerName = "John",
                            ItemName = "Card",
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
